[[DocApi]]
== Api in different languages

=== Apis Overview

Core objects, widgets and components can be created in different APIs, all leading to the same resulting object.

* Javascript is the most common and most powerful way
* HTML Custom Elements are available for widgets and components, i.e. for all visible objects
* JSP provides wrapper for object creation
* For XSLT named templates are available for creation of thr objects
* XAPI allows you to trigger creation of objects from XML

In the following chapters we show the same sample for each language API:

=== Javascript API

Javascript is the most common and powerful usage of BCD-UI objects.
As opposed to the other APIs, it is not declarative but instead you work wit the real objects.
Start by importing the library
[source,html,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=jsinclude]
----

For visual output of widgets, components and renderer, you need to create a targetHtml on you page
[source,html,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=rendererTH]
----

Best is to put your javascript code at the page bottom.
This way you are sure your targetHtml elements are created already:
[source,javascript,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=jscode]
----

=== HTML5 Custom Elements API

HTML5 Custom Elements look like standard HTML tags but provide custom functionality.
They will become more and more common in the next time.

.General rules Rules
* There are custom tags for widgets, components and the renderer, i.e. for all objects creating visual output.
* The naming of the tags follows the naming of the Javascript API, preceded by 'bcd-'.
* The output is placed at the location of the tag, i.e. no targetHtml is necessary
* To reference other objects, for example DataProviders, you need to give those objects and explicit id

Place the renderer or widget where you expect the output
[source,html,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=renderer5]
----
<1> For HTML5 Custom Elements, don't use self-closing elements ('/>'), use an explicit closing tab instead

Create non-visual objects with Javascript and make sure you assign an id
[source,javascript,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=model5]
----
<1> Assign an id because HTML5 Custom Elements need strings as parameters

=== JSP API

To use BCD-UI's taglib, make sure to add bcui-ui-jsptaglib.jar to WEB-INF/lib. +
Start by importing the taglibs needed on your page.

[source,jsp]
----
include::../../../BCD-UI-Tutorial/web/api/index.jsp[tag=taglibs]
----

Then use `<b:init/>` tag to load and start BCD-IU

[source,html]
----
include::../../../BCD-UI-Tutorial/web/api/index.jsp[tag=init]
----

Tags have the same name and parameters as their Javascript counterparts, except SimpleModel, which is named model in jsp.
Our tags allow tag nesting for parameters.
A renderer or widget will create its output at the place of the tag, so on this case you do not need a targetHtml parameter.

[source,html,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.jsp[tag=renderer]
----
<1> Output is placed where the tag is

=== XSLT API

You can call our named templates from XSLT to create BCD-UI objects, including core, widgets and components.
This is useful, if you have an XSLT creating HTML allowing very dynamic UIs. +
Such an XSLT may look like this:

.xsltApiSample.xslt making calls to XSLT API
[source,xml]
----
include::../../../BCD-UI-Tutorial/web/api/xsltApiSample.xslt[]
----
<1> Import bcdui/core/core.xslt, bcdui/widget/widget.xslt, bcdui/widgetNg/widgetNg.xslt and or , bcdui/component/component.xslt
<2> Embed the tags in yout ordinary HTML output
<3> The XSLT template names follow the js API names in lower case
<4> The parameter names follow the js API

First create a place where to show the result:
[source,html,indent=0]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=rendererXsltTh]
----

Then create a Renderer to show it and it will trigger the creation of the objects:
[source,javascript]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=rendererXslt]
----

.XSLT API Restrictions
* It is not possible to use core:modelUpdater on the guiStatus to initially transform it. Please use either JS or JSP API for that purpose.
* Following widgets from /bcdui/js/widget/widget.xslt are not available in this API: blindUpDown, loginForm, userMessagesEditor, userMessagesViewer

=== XAPI API

XAPI is a fully declarative way to create BCD-UI objects in XML.
It can be used directly and allows for easy creation of a Domain Specific Language (DSL) in XML for your customers on top of it.

An XAPI file looks like the following:

.xapi.xml making use of XAPI
[source,xml]
----
include::../../../BCD-UI-Tutorial/web/api/xapi.xml[]
----
<1> Tag and parameter names follow Javascript API
<2> You can freely mix and nest with HTML here

The minimal way to apply it is to create the following XSLT.
In your version you may want to extend this by your DSL functionality.

.xapiMinimalRenderer.xslt for applying XAPI
[source,xml]
----
include::../../../BCD-UI-Tutorial/web/api/xapiMinimalRenderer.xslt[]
----
<1> Add an html namespace so that we can copy that later 1:1
<2> Import needed xslt (see comment above XSLT API)
<3> You can freely mix and nest with HTML here
<4> Here we make sure we copy HTML content 1:1

And use the standard way to apply this stylesheet to the xapi file. Make sure you created the targetHtml before
[source,javascript]
----
include::../../../BCD-UI-Tutorial/web/api/index.html[tag=rendererXapi]
----
<1> A short way to create a SimpleModel and pass it

. XAPI Restrictions
* It is not possible to use core:modelUpdater on the guiStatus to initially transform it. Please use either JS or JSP API for that purpose.
* Following widgets from /bcdui/js/widget/widget.xslt are not available in this API: BlindUpDown, LoginForm, UserMessagesEditor, UserMessagesViewer

=== Create your own Domain Specific Language DSL

The real power of XSLT API and XAPI is that you can easily extend it to your own Domain Specific Language.

First extend the xslt used for the XAPI sample by an xslt template reflecting you DSL.
In our case we added `cust:MyRenderer`, which is convenient as it gets the data url directly, removing the need to create an extra DataProvider.
While this is a very simple example, you can easily extend it to a complete DSL.

.dslRenderer.xslt, defining your extension
[source,xml]
----
include::../../../BCD-UI-Tutorial/web/api/dslRenderer.xslt[]
----
<1> Use `xmlns:cust=http://www.businesscode.de/schema/bcdui/customization-1.0.0` namespace for your extensions as it is known to the browser's xpath, BCD-UI adds it there.
<2> This is where your DSL is handled, note the 'cust' namespace. You can create any HTML content and BCD-UI objects here. +
Here you may also call apply-templates to resolve nested XAPI calls in a more complex sample.
<3> Internally it will translate to calls to XSLT API
<4> Here the value of your 'dataUrl' parameter is passed
<5> Standard handling of XAPI

Create a renderer with the dslRenderer.xslt as `chain` an die following as `inputModel`

.dsl.xml, calling your extension
[source,xml]
----
include::../../../BCD-UI-Tutorial/web/api/dsl.xml[]
----
<1> Make sure to HTML content is in html namespace
<2> You can freely mix and nest with HTML content
<3> Here you make use of your custom DSL

and you will see your own DSL in action!