[[DocArchitecture]]
== Architecture

=== Architecture Overview

BCD-UI is a library for creating web applications such as ranging from simple data reporting and manipulation to complex OPM scenarios.
It consists of client and server side parts communicating via web services exchanging XML messages and data.
On server side services respond to web service requests and assure typical lifecycle tasks like security and caching.
On client side BCD-UI follows model view control MVC architecture.
In BCD-UI models are implemented as XML documents, the view is XSLT based and Javascript takes over the controller part.

==== Architectural principles

BCD-UI does make use the following architectural patterns

Web application:: This is the most obvious as BCD-UI applications are web applications.
The user interface is the browser, no installation is needed on the client side.
All artifacts are delivered in todays web standard technologies.
On client side any web application can be merged with BCD-UI.
J2EE:: On server side, BCD-UI applications are J2EE applications. Many artifacts are delivered as J2EE artifacts.
WebServices:: Data exchange between client and server is web service based, i.e. data is exchanged as XML and the request is send as XML.
In most cases the server side is state-less, keeping all states in database for optimal scaling.
Model View Control:: This pattern's implementation is done in the form that all data is kept as XML, user interactions are handled by JavaScript and the view part is realised by XSLT.
X-Forms:: X-Forms introduces a clear separation between data and the layout as required by the model view control pattern.
Visual elements do not keep their data inside but rather are bound to a model, which in turn keeps all data.
BCD-UI is not a X-Forms implementation though.
Multi-channel XSLT:: XSLT is used to display data in different ways and on different level of granularity to the user.
This views can be switched on the client without the need of server access, making different views easier and faster.

==== Usage model

In general, a carrier J2EE jsp page will request data as XML on the server,
keep that on the client as XML and transform the data to visible artifacts - like reports - with XSLT on the client.
To support this, both, ready-to-use server and client side elements are part of BCD-UI.
Many applications can be built with just these high-level elements. Extended use case can add more and more custom J2EE parts to it.
To apply BCD-UI you will typically just need to

. Create a standard J2EE application
. Add BCD-UI library support in form of some jar files and entries to web.xml
. Define your logical data model in BCD-UI's binding XML
. Create a standard jsp page as carrier
. Add widgets, like report filters, in the form of BCD-UI jsp tags to your page
. Add a report, provided for convenience as a jsp tag to your page

and you are done. A step-by-step example is given <<DocMinimalCube,here>>.

==== Layers

Several levels of abstractions are provided by BCD-UI.

Modules:: A BCD-UI module is composed of components and can support such complex tasks as providing a ScoreCard or data upload.
Modules are provided as a set of JSP tags cooperating in a work-flow or provided several dependent elements on a page.
Components:: Components are ready-to-use elements and cover standard reports, charts or grid data editors among others.
Components are provided as JSP tags and JavaScript elements to be used on the client, accessing server side functionality.
Widgets:: Widgets are small ready-to-use elements to display or gather input or to support navigation.
Samples are input fields, navigation menu or message boxes.
Infrastructure layer:: Many aspects of typical applications like caching or object live cycle of data historization are covered by the generic infrastructure layer.
As the elements above are built on top of each other, they share most of the server side infrastructure.
Server side infrastructure is mostly independent of the exact client element.
