[[DocCaching]]
== Caching

=== Caching overview

Caching is a mechanism to speed up performance drastically, next to database tuning it is the most important performance measure.
BCD-UI supports caching and makes caching setup easy.
It allows for reducing server and network load and improving user experience at the same time.
Depending on the type of expected access different caching strategies are optimal.
BCD-UI supports two types of caching

Client side caching:: Client side caching is often the most effective way of caching.
It prevents completely the need for repeated requests to a server.
No load at all is produced for network and server and the user sees the requested data immediately, more like in a desktop application.
Server side caching:: Server side caching use the cache on the server.
The clients need to do an actual request but repeated identical requests from multiple clients, like default reports, are answered with low overhead.

The definition of when a resource expires is done identically for server and client caching.
It is possible to define the 'expires' date of the answer for a request as a sample occurring at  `Tue, 01 Dec 2009 12:30:40 UTC`  in terms of

ExpiresAbsTime::  time, like "00:00:00" leading to  `Wed, 02 Dec 2009 00:00:00 UTC` 
ExpiresAbsDow::  day of week incl. hour, like "Sat-12" leading to  `Sat, 05 Dec 2009 12:00:00 UTC` 
ExpiresAbsDatetime::  absolute date time, like "2011-01-20 12:00:00" leading to  `Thu, 01 Jan 2011 12:00:00 UTC` 
ExpiresRelDays::  number of days starting from the request, same time, like "2" leading to  `Thu, 03 Dec 2009 12:30:40 UTC` 
ExpiresRelTime::  number of hours/min/sec starting from the request, like "01:00:05" leading to  `Tue, 01 Dec 2009 13:30:45 UTC` 
CacheRequestDirective::  native HTTP1.1 header string to be set in Cache-Control header

There can be multiple space separated values for ExpiresAbsTime and ExpiresAbsDow, like "00:00:00 12:00:00", the next matching one is used for the response expires.
The response will have the link:http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21[HTTP Expires, window="_blank"] header be set accordingly.

==== Disable Caching

During development, you do not usually have enable caching. For this case BCD-UI provides the possibility to enable/disable all caching settings.
To achieve this please define a environment entry within your context.xml file with the name: "bcdui/disableCache" like this:

[source,xml]
----
<Environment name="bcdui/disableCache" type="java.lang.Boolean" value="true"/>
----

RequestLifecycleFilter will send a Cache-Control: no-cache; no-store for all resources if set to true.

=== Client side caching

Client side caching is by far the most efficient way of caching in most cases.
ClientCachingFilter is responsible for adding caching information to the HTTP response.
Client filters also allow an ExcludeUrls parameter with a space separated list of regular expressions.
If an expression matches the request path, the filter takes no action.

Static files can usually be cached. How long depends on when a re-deployment may happen.
Typically if deployments happen over the week-end, set  `ExpiresAbsDow`  to 'Sat' as shown above.
To identify static files it is possible to define for which extensions the ClientCachingFilter applies via ExtensionsRestriction.

In a reporting environment, reporting and reference data can often be cached until the next morning.
This is supported by setting  `ExpiresAbsTime`  to '07:00:00'.
To support different caching times for different data, create different servlet instances at these URLs in your web.xml.

[WARNING]
Always exclude /bcdui/servlets/ and /bcdui/bcdui.js from caching.
In most cases you also want /vfs/ to update immediately.

The default link:https://github.com/businesscode/BCD-UI/blob/master/Server/configFiles/web.xml[web.xml^] contains 2 setups.
The one initially enabled is optimized for development, caching only BCD-UI sources, for production enable the second one, caching all static resources.


==== Other headers

For the client side header it is also possible to define the response header value of value of cache-directive with the `cache-response-directive` parameter.
See sample for no-cache below.
The response will have the link:http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9[HTTP Cache-Control, window="_blank"] header be set accordingly.

