[[DocContext]]
== Application context and settings

=== Unified Expression Language

The BCD-UI System uses the J2EE Unified Expression Language to put Server-side Values into
XML documents at various places. With this feature it is possible to create for example
request documents with the period set to the current month or year. This is especially
useful when such a request document is based on the guiStatus and therefore bookmarkable,
because the bookmark could contain a dynamically changed date.

==== Usage scenarios

There are some XML documents where the EL can be used. These documents are described in
the following sections.

Request document / GuiStatus:: The request document can make use of the EL to fill in some values (usually filters)
with server-side defaults.
Example:
+
[source,xml]
----
<Status xmlns="http://www.businesscode.de/schema/bcdui/guiStatus-1.0.0">
  <Filter xmlns="http://www.businesscode.de/schema/bcdui/filter-1.0.0">
    <Expression bRef="date" op="=" value="${session.defaultDate}"/>
  </Filter>
</Status>
----
+
WebRowSet Servlet:: This use case is applied when saving a WebRowSet on the server which should contain
server-defined values. Example
+
[source,xml]
----
<Wrs xmlns="http://www.businesscode.de/schema/bcdui/wrs-1.0.0">
  <RequestDocument/>
  <Header>
    <Columns>
      <C pos="1">
        <BindingItem id="countryId"/>
      </C>
      <C pos="2">
        <BindingItem id="countryName"/>
      </C>
    </Columns>
  </Header>
  <Data>
    <I>
      <U>${bcdfn:generateId("dataIds")}</U>
      <U>New Country</U>
    </I>
  </Data>
</Wrs>
----
+
In this WebRowSet the bcdfn:generateId function is used. This function generates a
new ID (e.g. from an Oracle Sequence) for a certain scope (e.g. the name of the Sequence).

Bindings:: The EL is used within the Bindings to set some default values for the Binding Items. These
values are evaluated by the WebRowSet servlet or other Servlets using Bindings to set some
default filters for columns. This technique makes it very easy to implement row-level
security.

==== EL variables and functions

The EL context defined by BCDUI offers access to the "request" and "session" variables. If the
EL occurs within an XML document it also defines a "document" variable pointing to the DOM
document. These variables "request" and "session" variables work similar to the ones defined
in JSP so that Expressions can be re-used. The context also contains the functions declared in
webpage.tld to makes it even more compatible with JSP.

==== Using EL within custom servlets

It is also possible to use the Expression Language within custom code. To achieve this an object
of the class  `de.businesscode.bcdui.el.ELEnvironment`  must be created and its
 `eval`  method can then evaluate all EL expressions within a specified String.
