[[DocConventions]]
== Conventions

=== Naming conventions

Within BCD-UI please follow the following naming conventions

* Namespaces format: http://www.businesscode.de/schema/bcdui/doc-1.1.0
* Package naming convention: de.businesscode.bcdui
* In js and jsp, xxRef is the string value of an id of the referenced object, for example modelRef is the id string of an referenced model
* Camel case for Java, XML etc is consequently only uppercase for the first letter of the word, even for abbreviations , HTMLElemet becomes HtmlElement
* BindingSet and BindingItem names are hard coded in th library, configuration of table names via bindings

=== Java

* Class inheritance is only from same or higher-level packages, i.e. derived classes always sit in sub-packages
* All classes accessing the database sit in a package xx.xx.db or below
* Sun link:http://java.sun.com/docs/codeconv/html/CodeConvTOC.doc.html[standard Java conventions, window="_blank"] apply

=== DB

DB tables and views of BCD-UI follow the following conventions, unless a customer requires different conventions

* Tables and views are not prefixed with V_ or T_ to be able to replace tables easily by views
* The name of the table follows the stored type in singular, if one row stores a single element, for example a table user will hold one user per row
* Tables storing customer's reference data have a prefix ref_ like ref_center
* Tables storing front end control information get a prefix fe_
* Tables storing history information from the reference data management get a _hist postfix, like ref_center_hist
* All classes accessing the database sit in a package xx.xx.db or below

=== JavaScript

* ids are camelCase starting with a lower case letter (myHtmlElement)
* Reference attributes to ids have the name of the referenced type plus ..Ref as a prefix as in bindingSetRef="someBindingSetId"
* Use map-style parameters for javascript calls
* Within the library all objects being passed are assumed to be existing. Only in the factory bcdui.package a withObjects() is necessary.
* Class name are in camel case starting with a capital letter (like InlineModel).

=== Tags

* Tags are thin wrapper around js only
* Only logic in tags beside parameter pass-through is creating a targetHtmlElement at the place of the tag

=== Terminology

Business Indicators:: Boolean indicating the result of a calculation

=== CEP terminology

The following is the generic terminology for CEP samples

* Center (was Terminal/Facility)
* Center functions: Origin/Destination Distribution Center (for pickup/delivery), hub (for domestic), Outbound/Inbound/Transit Hub (for international)
* Shipment
* Track event
* Track event code
* RCA root cause analysis
* Route (for lane, end-to-end)
* Route segment (for segment between centers)
* Route RCA report (was PAT)
* Local RCA report (was PTC)
* ScoreCard
* Avis (for shipment manifest)
