[[DocCoreArtifacts]]
== Core 

=== Using BCD-UI

==== Page core components

The following components are core on the client side of BCD-UI:

Model:: Models contain the data of the client like reporting data, reference data and data reflecting user selections.
On the client, all BCD-UI models store their data as XML documents, on server side data is stored in a relational database.
Models provide options for loading data, changing data, informing listener about changes, saving data back to the server
and loading additional data which is to be loaded deferred only on first access.
There is usually no need to provide project code for models but rather just configuration XMLs.
View:: Views provide the visual parts of the application like reports, edit grids, charts or widgets.
Views are implemented in XSLT, taking the model's XML as input for rendering HTML which is placed inside the page.
Views can be as simple as radio buttons and as complex as a ScoreCard.
New project specific views in the form of XSLT can be easily added within a project.
Controller:: The controller reacts on user interaction, like a button click or a drag and drop activity.
Controllers are small chunks of code implemented in js.
This code can be provided by BCD-UI library but can also be project provided code.
Next to user input, events thrown by model loading and changing activities can be used to trigger activities.
Widgets:: Widgets are small views for user information and interaction as input fields, the menu and fly-overs.
Widgets store they status per default in a page-wide _guiStatus_ to make it and its changes available for all parts of the page.
Components:: Components are more complex views like cubes or the charts, usually requiring a configuration XML.
Components themselves often consist of multiple views and widgets working together.
Page infrastructure:: Page infrastructure comprises the guiStatus, mechanisms for object life-cycle etc.
The guiStatus is the default model for all widgets and client-side status
and thus usually contains all selections done by the user in regards of data filter or selected tabs and so on.
Model requests use the guiStatus to decide data for which month is selected and view use it to decide which parts to display and which to collapse.
This infrastructure also covers generic tasks like client side exports or fly-overs.
Page layout structure:: Page layout structure is a set of HTML elements and css classes making up the over-all look and feel of the page frame in corporate a theme.

==== Server core componets

Core server components are:

WebServices:: WebServices exchange XML messages and data with the client model. <<DocXmlData,WrsServlet>> is the default service for data model requests.
Bindings:: Bindings translate between the logical data model of a BCD-UI application and the the physical databases.
WebServices use <<DocBinding,bindings>> to create the appropriate SQL for data reading and writing.
Servlets:: Several servlets provide all kinds of services to BCD-UI clients.
BCD-UI servlets are usually not addressed from users of BCD-UI directly.
Servlets are listed <<DocFilter,here.>>
Filter:: Filter control the traffic from and to the server under different aspects as security and caching.
Filters are listed <<DocFilter,here.>>

==== Delivered sources

Because BCD-UI applications are Java EE applications, most artifacts are typical Java EE elements.
BCD-UI is delivered in the form of

Java EE Server components:: Like Servlets and ServletFilters fulfilling server side tasks, for example access right evaluation or file upload.
WebServices:: WebServices server for XML exchange with the client mainly for database access.
JavaScript library:: JavaScript code forms the base for the client-side controller of the standard Model/View/Control pattern.
JSP tag library:: JSP tags are wrappers of the JavaScript functionality to ease their use on JSP pages.
XSLT library:: XSLT forms the base of vies of the standard Model/View/Control pattern.
Configuration files:: Configuration XML files allow to modify the behaviour of BCD-UI's components.

Each artifact can be extended or replaced by custom-written Java EE components implementing the appropriate interfaces.
