[[DocDebug]]
== Debugging

=== Debug facilities

Unzip gui status:: To see the guiStatus used in requests in their uncompressed form, send it as  `data`  parameter to zipLet, for example  `http://localhost:8080/webApp/bcdui/servlets/ZipLet?data=z2e-f7xPr3FQumlE...` 
Monitor network traffic:: Eclipse "TCP/IP Monitor" view as well as link:http://www.fiddler2.com/fiddler2[Fiddler, window="_blank"] can server as proxies to monitor network traffic exchanged between browser and server.
Server side logging:: log4j.propertes file in call path allows fine grained control of server side logging. Per default this is found in the /src/java folders of the template applications.
Endless waiting renderers:: use  `bcdui.factory.objectRegistry.getWaitingIds()`  to detect ids of renderer/wrapper, waiting for yet non-exisiting ids.
Find out which BindingItems a binding set has:: de.businesscode.bcdui.binding.Bindings.getInstance().get("b4_bsg_tte", java.util.Arrays.asList("cage_dy"))
And to read information about a specific one:: de.businesscode.bcdui.binding.Bindings.getInstance().get("b4_bsg_tte", java.util.Arrays.asList("cage_dy")).get("cage_dy").getJDBCDataTypeName()
Use the browser developer console to examine client issues:: Most modern browser have a console, where you can execute issue javascript commands to examine object status
Use request parameter debug=true:: The debug request parameter makes the application more picky about javascript parameters and turns on client logging that might help.

=== Common error messages

ERROR - Internal stylesheet error. this['node-set']= function (x) { return x; } 0 0 Unzip gui status:: This error message occurs if an import of a stylesheet fails inside of an stylesheet. The nodeset function is usually the first
 line after the include statement
IE: An Invalid character was found in text content. Or: Switch from current encoding to specified encoding not supported.:: Falsches encoding im xsl:output
FF: XSLT error codes (note, in general in IE the XSLT errors are much easier to debug):: link:https://developer.mozilla.org/en/Table_Of_Errors#XSLT_Errors[FF XSLT error codes, window="_blank"]
IE: stack overflow at line: 0:: Is often related to an IE caching issue, in many cases it goes away with caching being enabled.
