[[DocFilter]]
== Servlet Filters

=== Overview

==== BCD-UI Filters and Servlets

BCD-UI comes with the following filters and servlets, which are already mapped to their places in the default web.xml of BCD-UI:

These the only servlets which the user of BCD-UI uses or configures directly under normal circumstances.

WrsServlet:: Serves data in the form of a <<DocXmlData,Wrs web row set>> as reponse to a webrow set request.
It is mapped twice to allow parts to be client side cached and other not to be cached.
This is the only servlet used directly by non-BCD-UI library code.
Maps to bcdui/servlets/wrsServlet and bcdui/servletsCached/WrsServlet.
ClientCachingFilter:: Allows to control <<DocCaching,client-side caching>>.
Can be instantiated multiple times to allow different caching starategies for different parts.
It is recommended to map to all static resources and to slow changing reference data served for example at bcdui/servletsCached/wrsServlet.
Maps to parts to be cached as per project need.


===== Backgound servlets and filters

The following servlets do their work in background. Users of BCD-UI usually do not get in direct contact with them

RequestLiveCycleFilter:: Manages livecycle of BCD-UI server objects. Maps to the full application.
StaticResourceServlet:: Severs static resources like js or img files from the library which are packaged in bcd.jar.
They are mapped to there logical places and appear to be located at WebContent/bcdui.
Maps to bcd-ui library parts.
BCDUIConfig:: Serves initial configuration information for BCD-UI frontend library.
Maps to bcdui/servlets/config.js.
ZipLet:: Allows the library a more efficient data exchange between client and server and prevents URLs becoming too long.
Maps to bcdui/servlets/ZipLet.
