[[DocGettingStarted]]
== Getting Started

To start developing BCD-UI from scratch, just follow these three steps:

Setup your development environment ::
  * Get your IDE and a Java EE web server up and running
  * Add some BCD-UI files to your IDE to easy development with auto-complete support
  * See chapter <<DocBootstrap,Bootstrap>> for these steps
Setup an BCD-UI web application ::
  * Create a standard web application with your IDE
  * Add bcdui.jar to WEB-INF/lib, we use gradle for this task
  * Add a standard database connection to your web application container
  * Copy some entries to web.xml
  * See chapter <<DocAppsetup,Application Setup>> for these steps
Add pages to your web application ::
  * BCD-UI pages are standard HTML pages with some divs needed by the theme and a single bcdui.js file being loaded
  * See chapter <<DocSimpleReq,Simple request>> and later chapter <<DocMinimalCube,Minimal Cube>> for this

=== Overview

This section is about creating a simple BCD-UI project in Eclipse IDE using gradle build tool.
The BCD-UI project has security enabled and supports login authentication.
It provides a simple page with database content depending on user input.
While the section shows the setup using the popular IDE Eclipse in detail, it can be done with any IDE of your choice, Eclipse is not a requirement.

The steps to create the Getting Started application are:
 
. Development environment setup. Get Java, Eclipse and Tomcat to set up your development environment.
. Application setup.
. Connect the application to a database
. Create a Login Page
. Create a simple page with a database access

Each step is described in the following sub chapters.
 
=== Step by step

==== Development environment setup

This step is required only once when starting to work with BCD-UI; subsequent projects can re-use the same environment.
To start working with BCD-UI you need some tools installed, mainly Java, an IDE like Eclipse and a Java web server like Tomcat.
Follow the <<DocBootstrap,bootstrap>> description.

==== Application setup

This step is only required once when starting a new BCD-UI application; subsequent pages or reports will re-use the same environment.

. Copy of dependencies.gradle to project root folder and execute gradle refresh dependencies
. Add entries to web.xml
. Add entries to context.xml

That's all, see more details in these <<DocAppsetup,instructions>>.

==== Connect the application to a database
To avoid setting up a database and test data from scratch, you can simply connect to an existing database and adjust the table and column information
accordingly.

To connect the web application to a database, we configure a datasource in our Tomcat.
This can be done in the application context file, which is located in WebContent/META-INF/context.xml.
We configure a datasource as follows. Please adjust the username, password, driverClassName and url to match your RDMBS.
Please be aware that the JDBC driver file needs to be in your tomcat/lib directory, WEB-INF/lib is not enough.
Some databases require specific additional attributes for full support, please have a look at
link:https://github.com/businesscode/BCD-UI/blob/master/Server/configFiles/tomcat/context.xml[BCD-UI/Server/configFiles/tomcat/context.xml, window="_blank"] there you will
find a sample for your database. 

The context file below has some settings to disable the BCD-UI and Tomcat caching mechanism.
These are the context attributes antiResourceLocking and cachedAllowed for the Tomcat server and
the environment settings bcdui/disableCache = true for the BCD-UI caching. 
The configuration shown is for Tomcat 8. Please refer the documentation for other versions of Tomcat or other Java web servers.

[source,xml]
----
<Context reloadable="true" antiResourceLocking="false">
  <Resources cachingAllowed="false"/>
  <Environment name="bcdui/defaultConnection" type="java.lang.String" value="jdbc/bcduidemo"/>
  <Environment name="bcdui/disableCache" type="java.lang.Boolean" value="true"/>
  <Resource name="jdbc/bcduidemo"
            auth="Container"
            type="javax.sql.DataSource"
            maxActive="10"
            maxIdle="2"
            maxWait="15000"
            testOnBorrow="true"
            driverClassName="your_driver_class_name"
            url="jdbc:your_database"
            username="your_username"
            password="your_password"/>
  <WatchedResource>WEB-INF/web.xml</WatchedResource>
</Context>
----
To continue the tutorial, we assume there is table containing data like shown in the following table:

[options="header"]
|===
|id|dy|country|station|cars_sold|cars_repaired
|10001|2017-01-01|DE|Cologne|50.0| 25.0
|10002|2017-01-02|FR|Paris|1.0|66.0
|10003|2017-01-03|DE|Berlin|75.0|334.0
|10004|2017-01-04|US|New York|17.0|43.0
|10005|2017-02-05|DE|Cologne|29.0|43.0
|10006|2017-02-06|ES|Barcelona|27.0|10.0
|10007|2017-02-07|DE|Cologne|21.0|13.0
|...|...|...|...|...|...|
|===

The <<DocBinding,BindingSet>> mapping for this table looks like this:

[source,xml]
----
<BindingSet xmlns="http://www.businesscode.de/schema/bcdui/bindings-1.0.0" id="testData" table="test_data">
  <C id="id" caption="Id" isKey="true">
    <Column>id</Column>
  </C>
  <C id="dy" caption="Dy">
    <Column>dy</Column>
  </C>
  <C id="country" caption="Country">
    <Column>country</Column>
  </C>
  <C id="station" caption="Station">
    <Column>station</Column>
  </C>
  <C id="carsSold" caption="Cars sold">
    <Column>cars_sold</Column>
  </C>
  <C id="carsRepaired" caption="Cars repaired">
    <Column>cars_repaired</Column>
  </C>
</BindingSet>
----

Create a similar file in `WEB-INF/bcdui/bindings` and name it testData.xml.

TIP: By convention, the BindingSet's filename is the same as the binding set's `id` plus '.xml' extension.

The BindingSet is validated and enriched by database catalog information during the startup of the web application.
So typos in column names or not existing columns are detected already. The output can be found in the tomcat console.

----
2017-03-08 10:59:31  ReadBindingSet: BindingSet 'test_data': org.postgresql.util.PSQLException: ERROR: column t3.unicorns_feeded does not exist
----

In case a binding set is not correct, it is ignored by BCD-UI so that any access to it would lead to a BindingNotFoundException.
The columns elements bnd:C are enriched during startup and BCD-UI knows the type, size, not-null and other properties.
Important for our next steps in this section are the ids. So, to tell BCD-UI components what table to access we would then use
id="testData" and if we specify a certain column, we use the value of the id attribute of the desired column.

==== Create Login Page

The next step is to enable the security filter and to create a login page. This is optional.
Here are the detail instructions on how to setup everything: <<DocLogin,Login Page>>.

==== Create Simple Request Page

The next step is to create a simple page that retrieves data filtered by some user input.
Detailed instructions can be found <<DocSimpleReq,here>>.
