[[DocPageStructure]]
== Client infrastructure

This chapter describes the life-cycle of BCD-UI artifacts on a client HTML page.
Understanding this flow of events is crucial to working with BCD-UI.

=== Page live-cycle

BCD-UI pages are standard HTML pages.
You can mix BCD-UI with any other HTML technology or HTML-based library. +
For BCD-UI artifacts, the following flow of events applies.
All events are fully asynchronous.

Page-Loading phase::
. The page is loaded by the browser
. BCD-UI live-cycle artifacts are constructed
. `bcdui.wkModels.guiStatus` singleton, per default holding information of the user's selection like chooser settings,
is initialized from the guiStatus parameter of the pages's URL.
. `bcdui.wkModels.guiStatusEstablished` singleton is constructed. It is a frozen copy of guiStatus
. Any ModelUpdater on guiStatus and guiStatusEstablished are executed and then both become _ready_
. Renderer on the page responsible for building the visible parts like widgets, edit grids and reports execute themselves.
Only Renderer execute themselves, all other AbstractExecutables wait to be executed.
. The renderer ask their input and parameter link:../jsdoc/bcdui.core.DataProvider.html[bcdui.core.DataProviders^] to execute.
. DataProvider can depend on other data providers as input.
Thus, *DataProviders form dependency trees*, which execute recursively.
Only once all needed input and parameter data providers have become ready, a DataProvider proceeds the execution and becomes ready itself.
See <<DataProviders,chapter on DataProviders>> below for more details.
. Once its input is ready, each Renderer creates its associated views and displays it

Page-Interaction phase::
* The user can use widgets and views to provide input and settings.
* Each activity of the user results in some change of a DataProvider.
** Changes to the UI, like chooser settings or sorting per default lead to changes in the guiStatus.
** Changes to business data will be stored separate DataProviders.
** Please note, no change of model data triggers any change of any view per se. +
Instead you setup listeners, that inform Renderer to refresh, if needed.
* A _save_ on a DataProvider event will sending the data to the associated web-service, usually WrsServlet, which then stores the data into the database.
* Other activities like in-place drill down will lead to additional data being loaded.

Page-Leaving phase::
* Pressing apply, menu navigation or drill-over events will cause the browser to leave the page.
* A call to link:https://businesscode.github.io/BCD-UI-Docu/jsdoc/bcdui.core.lifecycle.html#.applyAction[applyAction^] will in addition append the current guiStatus as a parameter to the called URL, thus the new page will initialize its settings according to the chooser of the calling page.

=== guiStatus Singelton

BCD-UI instantiates a well-known `guiStatus` along with a frozen guiStatusEstablished copy in each page loading phase.
The guiStatus is a standard StaticModel, but is object of the following extra-handling:


* It can be found at `bcdui.wkModels.guiStatus` / `bcdui.wkModels.guiStatusEstablished`
* They have the fixed id _guiStatus_ / _guiStatusEstablished_
* It is initialized during page load with the guiStatus URL parameter of the page and executed.
It is guaranteed to be _ready_ when executing code in `bcdui.core.ready( function() { myCode } )`.
* It is the default target model for widgets, i.e. it applies if an xpath does not start with an explicit $modelId
* It is an implicit parameter to all transformations, for example in XSLT it can be access with +
`<xsl:param name="guiStatus"/>;`
* The link:https://businesscode.github.io/BCD-UI-Docu/jsdoc/bcdui.core.lifecycle.html#.applyAction[applyAction^] appends its content to the url of the called page
** Base64 encoding is used to make it URL friendly and it is compressed to prevent it from exceeding IE's URL length restriction
* guiStatusEstablished reflects best the values of the page loading phase and is not influenced by later user activity
* On server side it is decompressed and decoded by a servlet filter and provided via +
`getHttpRequest().getAttribute("guiStatusDoc");`

[[DataProviders]]
=== DataProviders

One main concept on client side of the BCDUI library are link:../jsdoc/bcdui.core.DataProvider.html[bcdui.core.DataProviders^]. +
All these objects offer a getData() method returning their data (XML, String etc.), which can be used by other objects.
DataProviders construct their data in different ways

* Some DataProvider like SimpleModel send HTTP GET or POST request to the server when executed.
  This can be any URL for a static file for example or a <<DocXmlData,request document>> to WrsServlet.
  ** On server side for each request, the web services evaluate the request documents and consult the binding definitions for the appropriate places in connected databases.
    The <<DocBinding,BindingSets>> translate the requested logical data ids into physical databases, views, tables and columns.
* Some DataProviders, like the ModelWrapper, apply XSLTs and another transformation rules to their input data and provide the result as their data.

==== Available data providers

This is the list of available data providers and their action on `execute()` to become _ready_.

SimpleModel:: A load data from a url.
The source can be static or a <<DocXmlData,Wrs request document>> to contact the WrsServlet.
If it is in autoRefresh mode, it will reload whenever the request document changes.
Auto-refresh mode is useful to load for small data immediately on user interaction.

StaticModel:: Receiving its data in form of a string or JSON.

ModelWrapper:: Executes a chain of transformations like XSLTs on its input data.
The input model is not changed.

ModelUpdater:: Similar to ModelUpdater but replaces the target model's content with the transformation result.

Renderer:: Executes a chain of transformations like XSLTs and inserts the result into the page's HTML at targetHtml.
The input model is not changed.

ConstantDataProvider:: Holds a scalar data type String|Number|Boolean, usefull for parameters

PromptDataProvider:: Prompts the user for a string input.

DataProviderWithXPath:: Gets a source data provider and an xPath and provides the evaluated xPath.

Calling `execute(true)` on a data provider will enforce the data provider to re-execute even in it is already in ready-state.
DataProviders inform their listeners about change events so that they can update.
You can find the API documentation here link:../jsdoc/bcdui.core.DataProvider.html[bcdui.core.DataProvider^].

===== Object Registry

`bcdui.factory.objectRegistry` is a singleton constructed by BCD-UI in page load.
Objects are registered if they get an explicit id assigned. +
DataProviders are plain javascript objects, which you can use via their javascript API.
But whenever you want to address a DataProvider by id in a declarative API, you need to give the DataProvider an explicit id on creation.
Examples are HTML Custom Element parameters or an xpath in targetModelXPath. +
If you provide such an id parameter, the object is centrally registered and can be retrieved by its id later.

[source,javascript]
----
var m1 = new bcdui.core.StaticModel( { data: "<Root a='1'/>" } ); // <1>
var m2 = new bcdui.core.StaticModel( { id: "myId", data: "<Root a='2'/>" } ); // <2>

m1.execute(); // <3>
var targetModelXPath = "$myId/@a"; // <4>
var m22 = bcdui.factory.objectRegistry.getObject("myId"); // <5>
----
<1> Standard way, no id assigned, the object is not registered
<2> An id is assigned for access from declarative APIs. The object is automatically registered.
<3> Ase the StaticModel from Javascript
<4> Access by id in an xpath, for example a targetModelXpath of a widget
<5> Retrieve the Javascript object from the `bcdui.factory.objectRegistry`, resulting to m22 === m2.

===== Dependency Tree

DataProviders and Renderers from dependency trees and automatically take care that their input is _ready_ and executed if not.
If you want to use such a DataProvider
See the following examples:

[source,javascript]
----
// Dependency tree is automatically taken care for from BCD-UI objects
var m1 = new bcdui.core.SimpleModel({ url: "mydata.xml" }); // <1>
var mw1 = new bcdui.core.ModelWrapper({ inputMidel: m1 }); // <2>

// When accessing from js, you need to make sure the DataProvider is ready
var m2 = new bcdui.core.SimpleModel({ url: "mydata.xml" });
console.log( m2.isReady() ); // Outputs 'false' <3>
// null === m2.getData(); <4>
m2.execute();
m2.onReady(
  function() { // <5>
    console.log( m2.isReady() ); // Outputs 'true'
    m2.getData();
  }
);

// Wait for multile DataProviders
bcdui.factory.objectRegistry.withReadyObjects(  m1, m2, // <6>
  function() {
    ...
  }
);
----
<1> SimpleModel will nor load until execute() is called by someone
<2> BCD-UI objects will call execute() on any of their input, of it finds it not _ready_.
Here mw1 will execute m1 and wait for m1 to become ready before continuing with its own action.
<3> The newly created SimpleModel m2 is not ready to be used, getData() will return null
<4> Call execute() explicit in this situation and wait for it to become ready
<5> Note, execute() is always asynchronous, except for StaticModel
<6> There are helper functions to wait for multiple DataProviders