[[DocVfs]]
== Virtual File System (VFS)

=== Virtual File System (VFS)

The Virtual File System (VFS) allows you to store resources in the database and make them available like real physical resources.

As an example you can take the cube template editor. It makes use of the VFS. The report layout is stored in the database as an XML file which can be
accessed at runtime via the path "/vfs/reports/myTestCube/layouts.xml".
You can even store, modify, reload <<DocBinding,binding files>> in the database. They will have a higher priority than static ones with the same id.

==== VFS Setup

For the virtual file system you need a database table and a corresponding binding set with the well known id "bcd_virtualFileSystem",
see link:https://github.com/businesscode/BCD-UI/blob/master/Server/wellKnownBindingSets/bcd_virtualFileSystem.xml[bcd_virtualFileSystem.xml^]

The columns in detail:

path:: The path under which the stored data is available. For example: "/vfs/reports/MyReport/MyReportLayouts.xml"
resourceClob:: A clob object holding the data. For example (cube template):
resourceBlob:: A blob object holding the data.
isServer:: A 0/1 value specifying is the data is a server-only (= 1) resource and won't be available on client side.


==== VFS reading, writing, refreshing and VFS Bindings
As mentioned, data from the VRS is accessible via the given path.
So you can e.g. create a model out of the stored data like this:

[source,javascript]
----
new bcdui.core.SimpleModel({url: bcdui.contextPath + '/vfs/reports/myTestCube/layouts.xml'})
----

Writing can be achieved by sending a wrs request to the server, e.g. with the help of an automodel.

[source,javascript]
----
var vfs = new bcdui.core.AutoModel({bindingSetId: "bcd_virtualFileSystem", bRefs: "path resourceClob" });
vfs.execute();
/* now modify your path in that model (/*/wrs:Data/wrs:R/wrs:C[1]) and resourceClob (/*/wrs:Data/wrs:R/wrs:C[2]) */
/* and store it back via sendData*/
vfs.sendData();
----

After writing data to the VFS you might need to refresh the cache to make the changes active.
You can do this by calling the CacheManager servlet with an action parameter:

[source,javascript]
----
jQuery.ajax({
  method: "GET",
  url : bcdui.contextPath+ "/bcdui/servlets/CacheManager?action=refreshVFS",
  success : function (data, successCode, jqXHR) { /* do something */ }
});

----
Available action values are: refreshVFS:: clears the VFS cache.
